### ISSUE TITLE
Vercel的环境变量

### ISSUE THREAD

**Issue by sysfox** [kkfive/kkapi-open#1]
1.作者能给一个DATABASE_URL的完整示例吗，文档把我整懵了
2.jwt字符串怎么生成啊

**Comment by Liynw** [comment]
> 1.作者能给一个DATABASE_URL的完整示例吗，文档把我整懵了 2.jwt字符串怎么生成啊

问题解决了吗，那个 jwt 是加密什么字符串，又是怎么弄的？谢谢！

**Comment by kkfive** [comment]
> > 1.作者能给一个DATABASE_URL的完整示例吗，文档把我整懵了 2.jwt字符串怎么生成啊
> 
> 问题解决了吗，那个 jwt 是加密什么字符串，又是怎么弄的？谢谢！

 jwt 加密字符串随便写即可，例如123，他的作用是用此字符串加密明文，为了不被破解，请将此字符串设置复杂一些

**Comment by Liynw** [comment]
> > > 1.作者能给一个DATABASE_URL的完整示例吗，文档把我整懵了 2.jwt字符串怎么生成啊
> > 
> > 
> > 问题解决了吗，那个 jwt 是加密什么字符串，又是怎么弄的？谢谢！
> 
> jwt 加密字符串随便写即可，例如123，他的作用是用此字符串加密明文，为了不被破解，请将此字符串设置复杂一些

谢谢！
