### ISSUE TITLE
GitHub 授权功能在授权完毕回调之后会强制把页面重定向至 domain.com/speak

### ISSUE THREAD

**Issue by Liynw** [kkfive/kkapi-open#3]
如果我的页面不是叫 `speak` 而是叫别的，那么就没办法正常使用 GitHub 授权功能

给个 Demo：https://oi.saiodgm.gq/bber/

**Comment by kkfive** [comment]
1. 你的kkapi GitHub配置好像有问题，无法获取token
2. ispeak有一个配置项`speakPage`默认为`/speak`，根据你得情况可以改成`/bber/`试试

![image](https://user-images.githubusercontent.com/82026204/185822577-1dee4ef5-7723-488f-8b99-ba808b1ef5fc.png)
